Azure/kubernetes-keyvault-flexvol

- README.md
> Update set-policy to remove list

- deployment/kv-flexvol-installer.yaml
- deployment/nginx-flex-kv.yaml
> bump v0.0.6 - support multiple kv objects

- README.md
- docs/traefik-tls-certificate.md
- docs/traefik-tls-certificate/configmap.yaml
- docs/traefik-tls-certificate/deployment.yaml
- docs/traefik-tls-certificate/echo-apple-ingress.yaml
- docs/traefik-tls-certificate/echo-apple.yaml
- docs/traefik-tls-certificate/identity.yaml
- docs/traefik-tls-certificate/rbac.yaml
- docs/traefik-tls-certificate/service.yaml
Adds more documentation about KeyVault, in particular how to fetch the different parts of a KeyVault Certificate using keyvault flexvol.
> doc: add documentation about keyvault + details about certificates

- azurekeyvault-flexvolume/Makefile
- azurekeyvault-flexvolume/keyvaultFlexvolumeAdapter.go
- azurekeyvault-flexvolume/main.go
- deployment/flexvol-installer/kv
> Add useragent and update Makefile

- azurekeyvault-flexvolume/Makefile
- azurekeyvault-flexvolume/main.go
- deployment/flexvol-installer/kv
- deployment/kv-flexvol-installer.yaml
Fixes #83 
- parse error log to return to pod
- redirect stderr
- bump v0.0.9
> Fix logging issues

- README.md
Update the README to match the example pod spec.
> doc(readme): update fields in readme for clarity

- CONTRIBUTING.md
- README.md
GitHub [community standards](https://github.com/Azure/kubernetes-keyvault-flexvol/community) expects a standalone `CONTRIBUTING.md` document in the project root.
> Separate "Contributing" doc

- azurekeyvault-flexvolume/Gopkg.lock
- azurekeyvault-flexvolume/Makefile
- azurekeyvault-flexvolume/main.go
- deployment/flexvol-installer/kv
- deployment/kv-flexvol-installer.yaml
> bump version

- deployment/kv-flexvol-installer.yaml
> bump to v0.0.13

- deployment/flexvol-installer/kv
Stop logging sensitive information
Fixes https://github.com/Azure/kubernetes-keyvault-flexvol/issues/125
> Don't log AAD Client Secret

- README.md
- azurekeyvault-flexvolume/Gopkg.lock
- azurekeyvault-flexvolume/Makefile
- azurekeyvault-flexvolume/keyvaultFlexvolumeAdapter.go
- azurekeyvault-flexvolume/main.go
- azurekeyvault-flexvolume/oauth.go
- deployment/flexvol-installer/kv
- deployment/kv-flexvol-installer.yaml
- deployment/nginx-flex-kv-deployment.yaml
- deployment/nginx-flex-kv-podidentity.yaml
- deployment/nginx-flex-kv.yaml
- docs/istio-tls-certificate.md
- docs/istio-tls-certificate/istio-ingressgateway-1_0_6.yaml
- docs/traefik-tls-certificate.md
- docs/traefik-tls-certificate/deployment.yaml
https://github.com/Azure/kubernetes-keyvault-flexvol/issues/78#issuecomment-524011386
Fixes https://github.com/Azure/kubernetes-keyvault-flexvol/issues/78
> Remove key vault read requirement

- README.md
- azurekeyvault-flexvolume/Makefile
- azurekeyvault-flexvolume/main.go
- deployment/flexvol-installer/kv
- deployment/nginx-flex-kv-managedidentity.yaml
> Bump version to v0.0.15; update README

- deployment/kv-flexvol-installer.yaml
> bump version in deployment

- README.md
- deployment/kv-flexvol-psp.yaml
- Add psp manifest to deployment dir
- Add note in README
Fixes https://github.com/Azure/kubernetes-keyvault-flexvol/issues/114
> add psp example to readme

- README.md
Add short documentation describing cloudname property for flexvolume keyvault setup.
Fixes #155 
Nothing, if I disregarded any important steps for this PR, please tell me, I'll correct asap.
> Documentation: add cloudname property documentation to README.md

- README.md
The sample code in OPTION 4: VMSS System Assigned Managed Identity was using the wrong parameter.
> Fixed Option 4 where wrong parameter was used in the sample code

- deployment/kv-flexvol-installer.yaml
Fix spelling errors, and add google cloud default
> Fix spelling errors, and add google cloud default 

- azurekeyvault-flexvolume/Makefile
- azurekeyvault-flexvolume/main.go
- deployment/flexvol-installer/kv
> bump version to v0.0.16

- deployment/kv-flexvol-installer.yaml
> bump version to v0.0.16 in deployment

- azurekeyvault-flexvolume/Makefile
- azurekeyvault-flexvolume/main.go
- deployment/flexvol-installer/kv
> bump version to v0.0.17

- deployment/kv-flexvol-installer.yaml
> bump manifests to v0.0.17

- README.md
> add eol message for 1.15
